### ISSUE TITLE
FR: provide a roadmap

### ISSUE THREAD

**Issue by r2evans** [nextcloud/user_oidc#150]
Is there a roadmap for this implementation of OIDC?

I recognize that docs are still pending (#12), but some of the issues (e.g., #7, #42, #90) suggest that it is not believed to be complete-enough yet, but ... I might be misinterpreting them, and some of those will be version-specific. (For instance, does 90 apply only to NC > 20?)

I'm not asking for you to speed up your programming, far from it. I'm migrating one of my installs to keycloak and am weighing how best to connect to it. I have been following https://github.com/pulsejet/nextcloud-oidc-login for a bit, but recognize that it is not a nextcloud-provided plugin. I'd prefer to stay with NC-proper if feasible and stable.

Do you have a milestone indicating when you think this will achieve a "v1" (ready for enterprise) status?

Thank you for everything!

**Comment by teutat3s** [comment]
I was able to connect to a keycloak server with the following steps:

1. In keycloak, create a new client, as `Root URL` enter your nextcloud's Domain, as `Valid Redirect URIs` enter https://your.nextcloud.domain/apps/user_oidc/code
2. Change `Access Type` to confidential, save, copy the `secret` from the `Installation` tab
3. In your nextcloud, find the OpenID Connect Setting in the Admin menu, choose an `Identifier`, set the `Client ID` to the one you chose in keycloak, paste the `secret` and enter the following as discovery endpoint:
```
https://{{keycloak-domain}}/auth/realms/{{realm-name}}/.well-known/openid-configuration
```

...aaand you should be able to login with keycloak.  The user management is funny though, because it seems the user is not created in nextcloud, too - so no idea how to add that keycloak user to e.g. a group in nextcloud.

**Comment by r2evans** [comment]
Thanks, @teutat3s.

I'm still learning keycloak and oidc in general, so I might be missing a point or two. I'm trying to use groups in the keycloak realm in addition to nextcloud groups. Ultimately, I'd like to use keycloak's "authorization" as well as "authentication", so that some users in the KC realm are not authorized access to nextcloud (even if they authenticate correctly. While this specific paragraph is off-topic for this issue, ultimately I'm wondering if there is any timeline, expected "release", and likely a list of still-to-be-implemented OIDC functionality.

**Comment by alerque** [comment]
> The user management is funny though, because it seems the user is not created in nextcloud, too - so no idea how to add that keycloak user to e.g. a group in nextcloud.

This is an understatement. I was able to get this working against my Keycloak instance, but I am migrating an existing Nextcloud instance that used an LDAP user backend. I can login with this plugin, but am dumped in new user profiles that are not linked to my previous users with no apparent way to map them. Also the users created via this plugin don't even register in `occ users:list` so I have no idea what to do next. Try the other [unofficial plugin](https://github.com/pulsejet/nextcloud-oidc-login) I guess.

**Comment by r2evans** [comment]
@alerque you said you are migrating from an LDAP backend to KC. Have you been successful with this or the other plugin? I'm facing an eventual migration from LDAP, and in testing it was problematic. I'm particularly concerned about retaining user settings and shares when I shift from "Joe Bob" in LDAP to "Joe Bob" in KC, where nextcloud will likely see them as separate users due to the different underlying IDs.

**Comment by alerque** [comment]
@r2evans I have been mostly successful so far but has been a bumpy road! I ended up using `user_saml` instead of this plugin because it was allowed the migration to happen in smaller steps and keep everything online in the mean time. With this plugin I couldn't figure out how to transition clearly at all. With SAML I was able to take over first authentication, then meta data transfer. I still haven't shut off LDAP entirely though, but it is disabled as an authentication mechanism.

The ugly part was at some point in order to get user data coming from Keycloak to start overriding the LDAP data I I had to redo my user tables to use usernames instead of the LDAP UUIDs they were saved with before. I wrote a script to run all the database queries and it worked, but finding all the places UUIDs needed rewriting to usernames is not something supported upstream. Another solution would have been to add all the original LDAP UUID data as an attribute in Keycloak, but then I would eventually end up with two classes of users in KC (those with LDAP history and those without) and mapping that was going to be a pain too.

**Comment by r2evans** [comment]
I've been wrestling with the differences between the two, where not all docs are in agreement (e.g., "authentication" vs "authentication *and* authorization"). Some docs assert that OIDC is not just better (JWS instead of XML), I've also seen that *"more modern systems including the requirement for OIDC in place of SAML"* (ref: https://auth0.com/intro-to-iam/saml-vs-openid-connect-oidc/). I'd much rather not have to migrate *again* in the near future :-)

Do you have enough work put into this to write up a gist or full repo with scripts and notes? I don't want to clobber this issue with side-bar commentary, and I wonder if there are more than the two of us considering migration from LDAP to OIDC or SAML.

**Comment by alerque** [comment]
@r2evans No I don't feel like I can document the process, there are too many things that could be different between systems. I did just post the database UUID→username remap script I used [in this Gist](https://gist.github.com/alerque/d7976cce609053cde589aa177e1bc2b6), use at your own risk. It worked for me but may not be 100% coverage for what other Nextcloud apps may store.

**Comment by juliushaertl** [comment]
There is some progress on the attribute mapping and implementing the missing pieces. Feel free to follow the created milestone for the progress https://github.com/nextcloud/user_oidc/milestone/1
