### ISSUE TITLE
Full Name in profile shows userid instead of Display Name

### ISSUE THREAD

**Issue by jimbojim** [nextcloud/user_oidc#525]
I'm using NextCloud 25, and KeyCloak. The userid  is showing up in the Full Name field but the Display Name seems to be properly set.

<img width="951" alt="image" src="https://user-images.githubusercontent.com/49759175/198806397-215490fe-ea2b-4d64-bee4-68ea93970005.png">

<img width="564" alt="image" src="https://user-images.githubusercontent.com/49759175/198806947-d1ef583f-33ea-4635-aac9-d75826837805.png">

<img width="871" alt="image" src="https://user-images.githubusercontent.com/49759175/198807482-c4d2118a-596f-4cd3-a147-0df6ad85f6ec.png">

**Comment by jacksgt** [comment]
Hello,

I can confirm this behavior with Nextcloud 24.0.5, `user_oidc` 1.2.1 and [Authentik]().

It seems that the `id` instead of the `username` gets shown in the header, because when I go to the `Users` admin screen, Nextcloud shows the correct user id and name.
So this might (?) actually be a bug in Nextcloud server, rather than user_oidc.
Furthermore, after disabling the option `Hash user IDs` in the `user_oidc` app, the user ID gets shown in the header (instead of the hash).

**Comment by julien-nc** [comment]
Thanks for reporting this issue.

The display name displayed in the user personal settings is obtained from the `oc_accounts_data` table which is not updated by the user_oidc user backend.

We can fix that either by
* making a change in server to get the display name from the user backend instead of the `oc_accounts_data` table
* making a change in user_oidc to make its user backend also affect `oc_accounts_data`

Not sure which way to go. @juliushaertl Any opinion?

**Comment by julien-nc** [comment]
I tried implementing the `ISetDisplayNameBackend` interface in the user_oidc user backend but then its `setDisplayName` is never called when calling `$user->setDisplayName()` ($user is an IUser).

**Comment by jacksgt** [comment]
That's a very interesting insight, thanks for taking a look!

How is this behaviour handled in the 'user_ldap' app?
From what I can see in the DB, that app correctly populates the 'oc_accounts_data' table.

https://github.com/nextcloud/server/tree/master/apps/user_ldap

**Comment by juliushaertl** [comment]
LDAP calls this method https://github.com/nextcloud/server/blob/dab5ea958a58e79b7f40b49bbe3af8839dc9c9d1/apps/user_ldap/lib/User/User.php#L391 which then emits a UserChangedEvent that updates the account data https://github.com/nextcloud/server/blob/92a5a8f075fe5e6b72037cc4a668090d3a8cacf5/lib/private/Accounts/Hooks.php#L80

But I'm not sure if that is the most elegant way to do that. Might be worth to double check also how that is done in the user_saml app

**Comment by juliushaertl** [comment]
> I tried implementing the `ISetDisplayNameBackend` interface in the user_oidc user backend but then its `setDisplayName` is never called when calling `$user->setDisplayName()` ($user is an IUser).

That event is to allow users to update their display name through Nextcloud in the implementing backend, so that would be the other way round.

**Comment by robertmx** [comment]
I poked around in the Nextcloud 25 DB and found, that the display name, that is visible in the web UI is not taken from oc_accounts_data but from oc_accounts. The oc_accounts table effectively contains a JSON-serialized representation of the data from oc_accounts_data.

I think it would be prudent to actually change user_oidc to set the correct values in these tables*, because setting the displayname property to some cryptic internal id is most likely not the intention of the NC data model. Going against the data model might exhibit other unintended side effects. For example the owner of a circle also uses that property.

cheers
Robert

* There might be some programmatic triggers, that generate one from the other, I didn't check that.

> Thanks for reporting this issue.
> 
> The display name displayed in the user personal settings is obtained from the `oc_accounts_data` table which is not updated by the user_oidc user backend.
> 
> We can fix that either by
> 
>     * making a change in server to get the display name from the user backend instead of the `oc_accounts_data` table
> 
>     * making a change in user_oidc to make its user backend also affect `oc_accounts_data`
> 
> 
> Not sure which way to go. @juliushaertl Any opinion?

**Comment by robertmx** [comment]
Looking at the other backends, the communication with the accounts data is realized via the UserChangedEvent. The corresponding listener then updates the corresponding tables.
I attached a patch, that fixes this user backend.
[fix_525_display_name.txt](https://github.com/nextcloud/user_oidc/files/9950164/fix_525_display_name.txt)

**Comment by juliushaertl** [comment]
Reference on how this is done in SAML: https://github.com/nextcloud/user_saml/blob/df218717c7eba9c72209cd8c5ca4327a0e5e8546/lib/UserBackend.php#L654

**Comment by robertmx** [comment]
> Reference on how this is done in SAML: https://github.com/nextcloud/user_saml/blob/df218717c7eba9c72209cd8c5ca4327a0e5e8546/lib/UserBackend.php#L654

Thanks for checking the other user backends. Looks similar (identical?) to the patch that I posted. I take that as evidence, that this is the "right" way to propagate the display name to the accounts system.

**Comment by jacksgt** [comment]
@julien-nc Thanks for your work on this :1st_place_medal:

**Comment by jimbojim** [comment]
@julien-nc I want to say THANK YOU!! for this fix. I have validated the fix in my keycloak environment.

**Comment by remram44** [comment]
Is there a way to fix the display name of existing users?

**Comment by jacksgt** [comment]
@remram44 I believe they automatically get fixed when the user logs in (since that is when the sync is triggered).
