### ISSUE TITLE
You must access Nextcloud with HTTPS to use OpenID Connect.

### ISSUE THREAD

**Issue by lknite** [nextcloud/user_oidc#747]
But, I am accessing it via https.  Maybe this error has something to do with nextcloud being deployed via kubernetes (and via a reverse proxy)?

Is there any way to override the setting?
.
.

![image](https://github.com/nextcloud/user_oidc/assets/92187614/7b6abeb1-dd41-447f-afbc-20ca78da624d)

(Thrilled to finally have a simple oidc configuration option.  Thank you.)

**Comment by nc-fkl** [comment]
Hi @lknite 

>> https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html

overwritting the settings can be done by setting the 'overwriteprotocol' => 'https' option in Nextcloud's config.php

I guess currently you are doing something like:

http**s**://nextcloud.vc-prod-k.home.net <-> reverse proxy <-> kubernetes cluster <-> htt**p**://nextcloud.instance , am i correct?

Please let me know if it helped you getting it up and running! :)

**Comment by meesvw** [comment]
Can you provide what reverse proxy you're using ? I resolved this issue by adding this to my docker-compose.yml file. However not sure if this will work for your Kubernetes environment:

```
    environment:
      - NEXTCLOUD_TRUSTED_DOMAIN=example.com
      - TRUSTED_PROXIES=traefik  // Container name of my reverse proxy
      - OVERWRITEPROTOCOL=https // This solved my issue
```

**Comment by lknite** [comment]
working on it

**Comment by lknite** [comment]
abandoning

**Comment by nerocide** [comment]
I came accross the same message, and noticed that nextcloud configuration files in pod was incorrect.

It had many occurrences of paramerters like `overwrite*` in config/* files.

This was caused by my numerous deployments, settings test etc, not cleaning remaining pvc/pv after removing nextcloud deployments and redeploying etc (you need to set `finalizers` to `null` to remove them).

After a fresh install (all previous pv/pvc removed), config looks clean again and i don't see a red message `Accessing site insecurely via HTTP. You are strongly advised to set up your server to require HTTPS instead.` in the `/overview` page anymore.
